name: source_gen_test
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ChenMingMing <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  source_gen: ^0.9.4+2
  build: ^1.1.4
  # source_gen_example:
    # path: ./example
  builder_example:
    path: ./builder_example
  
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.5.2

