name: websocketandweb
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ChenMingMing <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 path: ^1.4.1
 http_multi_server: ^2.0.6
 shelf: ^0.7.5
 shelf_web_socket: ^0.2.3
 web_socket_channel: ^1.0.13
 shelf_static: ^0.2.8

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
