name: quiver_test
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ChenMingMing <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  quiver: '>=2.0.0 <3.0.0'
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
