name: json_test
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ChenMingMing <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.6.0
  pedantic: ^1.0.0
  test: ^1.0.0
