name: build_test
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ChenMingMing <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 path: ^1.4.1
 sass: ^1.21.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build: ^1.1.4
  build_runner: ^1.5.2